Nous devons au préalable creer un dossier data_volume pour la gestion des volumes persistant
mkdir data_volume


contenu du fichier 
---------------------------------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-db
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:    
      - name: mysql-db
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: devops
          - name: MYSQL_USER
            value: ops
          - name: MYSQL_PASSWORD
            value: dev
        ports:
        - containerPort: 3306
        volumeMounts: 
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - name: mysql-storage
        hostPath:
          path: /home/vagrant/wordpress/data_storage/
          type: Directory









Ici le déploiement de WordPress dans K8S
